version: '3.8'

services:
  db:
    container_name: postgres-lesson-1
    image: postgres:14.0-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}
  backend:
    container_name: backend-nest-lesson-1
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - '3001:3001'
    environment:
      - API_PORT=${PORT}
      - API_HOST=${DB_HOST}
  # - TYPEORM_USERNAME=${TYPEORM_USERNAME}
  # - TYPEORM_PASSWORD=${TYPEORM_PASSWORD}
  # - TYPEORM_DATABASE=${TYPEORM_DATABASE}
  # - TYPEORM_PORT=${TYPEORM_PORT}
  # - TYPEORM_HOST=db
